###############################################################################
######################Plotting GRATING 1#######################################
plt.figure(1)
plt.title('Epoch 6/14/15 G1 with region selection and slope line')
plt.xlabel(r'Observed Wavelength ($\AA$)')
plt.ylabel('Flux (erg/s/cm^2/$\AA$)')
plt.axvline(x=1110,color='red'),plt.axvline(x=1130,color='red'),plt.axvline(x=1150,color='black'),plt.axvline(x=1190,color='black')
plt.plot(Grating_1_polyfitpoints[0][0], Grating_1_polyfitpoints[0][1], marker='o', markersize=10, color="red",zorder=2)
plt.plot(Grating_1_polyfitpoints[1][0], Grating_1_polyfitpoints[1][1], marker='o', markersize=10, color="black",zorder=2)
plt.plot(TWL2,TFS2,zorder=0)
plt.axis([900,1250,0,3*10**-14])
plt.plot(TWL2,poly_array_1,zorder=1)
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(13.5, 10.5)
savefig('\\Users\\micha\\Google Drive\\Documents\\Python Scripts\\PLOTS\\G1_Unnormalized')
###############################################################################
plt.figure(2)
plt.title('Normalized Epoch 6/14/15 G1 ')
plt.xlabel(r'Observed Wavelength ($\AA$)')
plt.ylabel('Flux (erg/s/cm^2/$\AA$)')
plt.axvline(x=1110,color='red'),plt.axvline(x=1130,color='red'),plt.axvline(x=1150,color='black'),plt.axvline(x=1190,color='black'),plt.axhline(y=1,color='orange')
plt.plot(TWL2,Normal_TFS1,zorder=0)
plt.axis([900,1250,0,3])
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(13.5, 10.5)
savefig('\\Users\\micha\\Google Drive\\Documents\\Python Scripts\\PLOTS\\G1_Normalized')
###############################################################################
###########################Plotting GRATING 2##################################
plt.figure(3)
plt.title('Epoch 6/14/15 G2 with region selection and slope line ')
plt.xlabel(r'Observed Wavelength ($\AA$)')
plt.ylabel('Flux (erg/s/cm^2/$\AA$)')
plt.plot(TWL1,TFS1,zorder=0)
plt.axvline(x=1175,color='red'),plt.axvline(x=1185,color='red'),plt.axvline(x=1345,color='black'),plt.axvline(x=1365,color='black'),plt.axvline(x=1395,color='purple'),plt.axvline(x=1402,color='purple'),plt.axvline(x=1420,color='orange'),plt.axvline(x=1460,color='orange'),plt.plot(Grating_2_polyfitpoints[0][0], Grating_2_polyfitpoints[0][1], marker='o', markersize=10, color="red",zorder=2),plt.plot(Grating_2_polyfitpoints[1][0], Grating_2_polyfitpoints[1][1], marker='o', markersize=10, color="black",zorder=2),plt.plot(Grating_2_polyfitpoints[2][0], Grating_2_polyfitpoints[2][1], marker='o', markersize=10, color="purple",zorder=2),plt.plot(Grating_2_polyfitpoints[3][0], Grating_2_polyfitpoints[3][1], marker='o', markersize=10, color="orange",zorder=2)
plt.plot(TWL1,poly_array_2,zorder=1)
plt.axis([1160,1470,0,3*10**-14])
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(13.5, 10.5)
savefig('\\Users\\micha\\Google Drive\\Documents\\Python Scripts\\PLOTS\\G2_Unnormalized')
###############################################################################
plt.figure(4)
plt.title('Normalized Epoch 6/14/15 G2 ')
plt.xlabel(r'Observed Wavelength ($\AA$)')
plt.ylabel('Flux (erg/s/cm^2/$\AA$)')
plt.plot(TWL1,Normal_TFS2,zorder=0)
plt.axvline(x=1175,color='red')
plt.axvline(x=1185,color='red')
plt.axvline(x=1345,color='black')
plt.axvline(x=1365,color='black')
plt.axvline(x=1395,color='purple')
plt.axvline(x=1402,color='purple')
plt.axvline(x=1420,color='orange')
plt.axvline(x=1460,color='orange')
plt.axhline(y=1,color='orange')
plt.axis([1160,1470,0,3])
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(13.5, 10.5)
savefig('\\Users\\micha\\Google Drive\\Documents\\Python Scripts\\PLOTS\\G2_Normalized')
##############################################################################
########################Plotting GRATING 3####################################
plt.figure(5)
plt.title('Epoch 6/14/15 G3 with region selection and slope line')
plt.xlabel(r'Observed Wavelength ($\AA$)')
plt.ylabel('Flux (erg/s/cm^2/$\AA$)')
plt.axvline(x=1425,color='red')
plt.axvline(x=1460,color='red')
plt.plot(Grating_3_polyfitpoints[0][0], Grating_3_polyfitpoints[0][1], marker='o', markersize=10, color="red",zorder=2)
plt.axvline(x=1500,color='black')
plt.axvline(x=1525,color='black')
plt.plot(Grating_3_polyfitpoints[1][0], Grating_3_polyfitpoints[1][1], marker='o', markersize=10, color="black",zorder=2)
plt.axvline(x=1590,color='purple')
plt.axvline(x=1605,color='purple')
plt.plot(Grating_3_polyfitpoints[2][0], Grating_3_polyfitpoints[2][1], marker='o', markersize=10, color="purple",zorder=2)
plt.axvline(x=1675,color='orange')
plt.axvline(x=1720,color='orange')
plt.plot(Grating_3_polyfitpoints[3][0], Grating_3_polyfitpoints[3][1], marker='o', markersize=10, color="orange",zorder=2)
plt.plot(TWL3,TFS3,zorder=0)
plt.plot(TWL3,poly_array_3,zorder=1)

plt.axis([1380,1770,0,7*10**-14])
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(13.5, 10.5)
savefig('\\Users\\micha\\Google Drive\\Documents\\Python Scripts\\PLOTS\\G3_Unnormalized')
##############################################################################
plt.figure(6)
plt.title('Normalized Epoch 6/14/15 G3 ')
plt.xlabel(r'Observed Wavelength ($\AA$)')
plt.ylabel('Flux (erg/s/cm^2/$\AA$)')
plt.plot(TWL3,Normal_TFS3,zorder=0)
plt.axvline(x=1425,color='red')
plt.axvline(x=1460,color='red')
plt.axvline(x=1500,color='black')
plt.axvline(x=1525,color='black')
plt.axvline(x=1590,color='purple')
plt.axvline(x=1605,color='purple')
plt.axvline(x=1675,color='orange')
plt.axvline(x=1720,color='orange')
plt.axhline(y=1,color='orange')

plt.axis([1380,1770,0,3])
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(13.5, 10.5)
savefig('\\Users\\micha\\Google Drive\\Documents\\Python Scripts\\PLOTS\\G3_Normalized')
###############################################################################
###############################################################################